name: firebase_ui_oauth_google
description: Firebase UI widgets for authentication & OAuth.
version: 1.2.11
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_oauth_google

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_auth: ^4.9.0
  firebase_ui_oauth: ^1.4.11
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"

flutter:
