name: firebase_ui_oauth_google
description: Firebase UI widgets for authentication & OAuth.
version: 1.3.2
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_oauth_google

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_auth: ^4.17.5
  firebase_ui_oauth: ^1.5.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"

flutter:
