name: firebase_ui_storage
description: Pre-built widgets and utilites that make it easy to integrate Firebase Storage into your Flutter app.
version: 1.0.1
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_storage/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

false_secrets:
  - example/**

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.2.6
  firebase_ui_localizations: ^1.6.1
  firebase_ui_shared: ^1.3.1
  path: ^1.8.2
  uuid: ^3.0.7
  file_selector: ^1.0.1
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2

flutter:
