name: "Detect changes"
description: "Detects which packages were changed"

outputs:
  changed_packages:
    description: "A JSON string containing the changed packages"
    value: ${{ steps.filter.outputs.changes }}

runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          firebase_ui_auth: 
            - 'packages/firebase_ui_auth/**/*.dart'
          firebase_ui_database: 
            - 'packages/firebase_ui_database/**/*.dart'
          firebase_ui_firestore:
            - 'packages/firebase_ui_firestore/**/*.dart'
          firebase_ui_localizations:
            - 'packages/firebase_ui_localizations/**/*.dart'
          firebase_ui_oauth:
            - 'packages/firebase_ui_oauth/**/*.dart'
          firebase_ui_oauth_apple:
            - 'packages/firebase_ui_oauth_apple/**/*.dart'
          firebase_ui_oauth_facebook:
            - 'packages/firebase_ui_oauth_facebook/**/*.dart'
          firebase_ui_oauth_google:
            - 'packages/firebase_ui_oauth_google/**/*.dart'
          firebase_ui_oauth_twitter:
            - 'packages/firebase_ui_oauth_twitter/**/*.dart'
          firebase_ui_shared:
            - 'packages/firebase_ui_shared/**/*.dart'
          firebase_ui_storage:
            - 'packages/firebase_ui_storage/**/*.dart'
