name: unit_tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  detect_changed_packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changed_packages }}
      has_changes: ${{ steps.filter.outputs.changed_packages != '[]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/changes_e2e
        id: filter

  android:
    runs-on: macos-13
    needs: detect_changed_packages
    if: needs.detect_changed_packages.outputs.has_changes == 'true'
    strategy:
      fail-fast: true
      matrix:
        package: ${{ fromJson(needs.detect_changed_packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - uses: bluefireteam/melos-action@v1
        with:
          melos-version: "3.0.1"
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
      - run: flutter devices
      - name: Run e2e tests
        run: |
          melos exec 
            --scope ${{ matrix.package }}_example 
            -c 1 
            --fail-fast
            -- flutter test integration_test/${{ matrix.package }}_e2e.dart
